import type { ModelDefinition } from "@/models.js";

/**
 * Third Culture Systems tier aliases.
 *
 * These are virtual "models" that callers select instead of a concrete
 * provider/model pair. The gateway's existing multi-provider routing picks the
 * cheapest healthy provider mapping and falls back to the next on failure, so
 * each tier doubles as a resilience group.
 *
 * Tier philosophy (revise by editing this file; see whatllm.org/explore):
 *   tcs-cheap       -> bulk classification/extraction at near-zero cost
 *                      (DeepSeek V4-Flash primary, Gemini Flash Lite fallback)
 *   tcs-balanced    -> default workhorse for most TCS services
 *                      (DeepSeek V4-Flash primary, Gemini Flash Lite + MiniMax
 *                      M2.7 fallbacks for capability headroom)
 *   tcs-reasoning   -> deeper thinking for complex multi-step tasks
 *                      (Kimi K2.6 primary, DeepInfra Kimi + Qwen3 235B
 *                      Thinking fallbacks)
 *   tcs-premium     -> highest quality, large context, world knowledge
 *                      (Gemini 3.1 Pro Preview on Vertex)
 *   tcs-vision      -> image understanding (receipts, screenshots, diagrams)
 *
 * Routing order within each tier is controlled by listing providers from
 * preferred primary -> fallbacks. Pricing fields are informational; actual
 * billed costs come from the underlying provider mapping. The gateway picks
 * the cheapest healthy mapping by default — so as long as W&B is healthy and
 * configured, tcs-cheap and tcs-balanced will route to V4-Flash.
 */
export const tcsModels = [
	{
		id: "tcs-cheap",
		name: "TCS Cheap",
		aliases: ["tcs-fast", "tcs-low"],
		description:
			"Third Culture cheap tier: near-zero-cost, fast model for bulk classification, extraction, and short summaries. Primary: DeepSeek V4-Flash on W&B Inference (CoreWeave) at $0.01/$0.01 per 1M tokens; fallbacks: Gemini 3.1 Flash Lite on Vertex, MiMo V2 Flash on Canopywave, MiniMax M2.7 Highspeed, Llama 4 Maverick on DeepInfra.",
		family: "tcs",
		releasedAt: new Date("2026-04-22"),
		providers: [
			{
				providerId: "wandb",
				modelName: "deepseek-ai/DeepSeek-V4-Flash",
				inputPrice: 0.01 / 1e6,
				outputPrice: 0.01 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 384000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "beta",
			},
			{
				providerId: "google-vertex",
				modelName: "gemini-3.1-flash-lite-preview",
				inputPrice: 0.25 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "beta",
			},
			{
				providerId: "canopywave",
				modelName: "xiaomimimo/mimo-v2-flash",
				inputPrice: 0.08 / 1e6,
				cachedInputPrice: 0.04 / 1e6,
				outputPrice: 0.24 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.7-highspeed",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "deepinfra",
				modelName: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
				inputPrice: 0.2 / 1e6,
				cachedInputPrice: 0.04 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "tcs-balanced",
		name: "TCS Balanced",
		aliases: ["tcs-default"],
		description:
			"Third Culture balanced tier: the default workhorse for most services. Primary: DeepSeek V4-Flash on W&B Inference — same model as tcs-cheap, but with a deeper fallback chain for reliability. Fallbacks: Gemini 3.1 Flash Lite on Vertex, MiniMax M2.7 on Fireworks/Together/Novita/MiniMax-direct, then Llama 4 Maverick on DeepInfra.",
		family: "tcs",
		releasedAt: new Date("2026-04-22"),
		providers: [
			{
				providerId: "wandb",
				modelName: "deepseek-ai/DeepSeek-V4-Flash",
				inputPrice: 0.01 / 1e6,
				outputPrice: 0.01 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 384000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "beta",
			},
			{
				providerId: "google-vertex",
				modelName: "gemini-3.1-flash-lite-preview",
				inputPrice: 0.25 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "beta",
			},
			{
				providerId: "fireworks",
				modelName: "accounts/fireworks/models/minimax-m2p7-instruct",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: 131072,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "beta",
			},
			{
				providerId: "together-ai",
				modelName: "MiniMaxAI/MiniMax-M2.7",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 196608,
				maxOutput: 196608,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "novita",
				modelName: "minimax/minimax-m2.7",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "minimax",
				modelName: "MiniMax-M2.7",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				splitTaggedReasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "deepinfra",
				modelName: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
				inputPrice: 0.2 / 1e6,
				cachedInputPrice: 0.04 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "tcs-reasoning",
		name: "TCS Reasoning",
		aliases: ["tcs-thinking"],
		description:
			"Third Culture reasoning tier: extended thinking for multi-step agent tasks, evidence verification, and long-form analysis. Primary: Kimi K2.6 on Parasail; fallbacks: Kimi K2.6 on DeepInfra/Moonshot/W&B, Qwen3 235B Thinking on W&B (cheap), Canopywave, Novita.",
		family: "tcs",
		releasedAt: new Date("2026-04-22"),
		providers: [
			{
				providerId: "parasail",
				modelName: "moonshotai/kimi-k2.6",
				inputPrice: 0.9 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				outputPrice: 3.8 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				stability: "beta",
			},
			{
				providerId: "deepinfra",
				modelName: "moonshotai/Kimi-K2.6",
				inputPrice: 0.75 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				outputPrice: 3.5 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 16384,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2.6",
				inputPrice: 0.95 / 1e6,
				cachedInputPrice: 0.16 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "wandb",
				modelName: "moonshotai/Kimi-K2.6",
				inputPrice: 0.95 / 1e6,
				cachedInputPrice: 0.16 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "wandb",
				modelName: "Qwen/Qwen3-235B-A22B-Thinking-2507",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				modelName: "moonshotai/kimi-k2.6",
				inputPrice: 0.5 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				outputPrice: 2.8 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "moonshotai/kimi-k2.6",
				inputPrice: 0.95 / 1e6,
				cachedInputPrice: 0.16 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "tcs-premium",
		name: "TCS Premium",
		aliases: ["tcs-best"],
		description:
			"Third Culture premium tier: highest quality with 1M context. Primary: Gemini 3.1 Pro Preview on Google Vertex (runs in our own GCP project); fallbacks: Kimi K2.6 on Moonshot/DeepInfra, GLM 5.1 on W&B.",
		family: "tcs",
		releasedAt: new Date("2026-04-22"),
		providers: [
			{
				providerId: "google-vertex",
				modelName: "gemini-3.1-pro-preview",
				inputPrice: 2 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				outputPrice: 12 / 1e6,
				pricingTiers: [
					{
						name: "Up to 200K",
						upToTokens: 200000,
						inputPrice: 2 / 1e6,
						outputPrice: 12 / 1e6,
						cachedInputPrice: 0.2 / 1e6,
					},
					{
						name: "Over 200K",
						upToTokens: Infinity,
						inputPrice: 4 / 1e6,
						outputPrice: 18 / 1e6,
						cachedInputPrice: 0.4 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.014,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "beta",
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2.6",
				inputPrice: 0.95 / 1e6,
				cachedInputPrice: 0.16 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "deepinfra",
				modelName: "moonshotai/Kimi-K2.6",
				inputPrice: 0.75 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				outputPrice: 3.5 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 16384,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "wandb",
				modelName: "zai-org/GLM-5.1",
				inputPrice: 1.4 / 1e6,
				cachedInputPrice: 0.26 / 1e6,
				outputPrice: 4.4 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32768,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "tcs-vision",
		name: "TCS Vision",
		aliases: ["tcs-multimodal"],
		description:
			"Third Culture vision tier: for tasks that need image understanding (receipts, screenshots, diagrams). Primary: Gemini 3.1 Pro Preview on Google Vertex; fallbacks: Kimi K2.5 on Moonshot, Llama 4 Scout on W&B (cheap).",
		family: "tcs",
		releasedAt: new Date("2026-04-22"),
		providers: [
			{
				providerId: "google-vertex",
				modelName: "gemini-3.1-pro-preview",
				inputPrice: 2 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				outputPrice: 12 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "beta",
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2.5",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "wandb",
				modelName: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
				inputPrice: 0.17 / 1e6,
				outputPrice: 0.66 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
